@IsTest
public class VehicleQueueableTestUtilityTest {
  @IsTest
    static void cover(){
        Test.startTest();
        VehicleQueueableTestUtility.methodToCoverage();
        VehicleQueueableTestUtility.methodToCoverage1();
        VehicleQueueableTestUtility.methodToCoverage2();
        VehicleQueueableTestUtility.methodToCoverage3();
        VehicleQueueableTestUtility.methodToCoverage4();
        VehicleQueueableTestUtility.methodToCoverage6();
        VehicleQueueableTestUtility.methodToCoverage5();
        VehicleQueueableTestUtility.methodToCoverage9();
        VehicleQueueableTestUtility.methodToCoverage7();
        VehicleQueueableTestUtility.methodToCoverage8();
        VehicleQueueableTestUtility.methodToCoverage10();
        VehicleQueueableTestUtility.methodToCoverage11();
        Test.stopTest();
    }
}